import userReadController from '#Controllers/user-read.controller.js';
import userRegisterController from '#Controllers/user-register.controller.js';
import userSearchItemController from '#Controllers/user-searchItem.controller.js';
import { Router } from 'express';
const userRoutes = Router();
userRoutes.post('/register', userRegisterController);
userRoutes.get('/list', userReadController);
userRoutes.get('/item/:uid', userSearchItemController);
userRoutes.get('/register');
export default userRoutes;
